[project]
name = "credscore"
description = "Decentralized credit scoring system"
authors = ["solidworkssa"]
telemetry = false
cache_dir = ".cache"

[contracts.credscore]
path = "contracts/credscore.clar"

[repl.analysis]
passes = ["check_checker"]
